/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RevendaRouteImport } from './routes/revenda'
import { Route as EscadasRouteImport } from './routes/escadas'
import { Route as EquipamentosRouteImport } from './routes/equipamentos'
import { Route as ElevadoresRouteImport } from './routes/elevadores'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as BstMonarchRouteImport } from './routes/bst-monarch'
import { Route as BstLinhaRouteImport } from './routes/bst-linha'
import { Route as IndexRouteImport } from './routes/index'

const RevendaRoute = RevendaRouteImport.update({
  id: '/revenda',
  path: '/revenda',
  getParentRoute: () => rootRouteImport,
} as any)
const EscadasRoute = EscadasRouteImport.update({
  id: '/escadas',
  path: '/escadas',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipamentosRoute = EquipamentosRouteImport.update({
  id: '/equipamentos',
  path: '/equipamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ElevadoresRoute = ElevadoresRouteImport.update({
  id: '/elevadores',
  path: '/elevadores',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const BstMonarchRoute = BstMonarchRouteImport.update({
  id: '/bst-monarch',
  path: '/bst-monarch',
  getParentRoute: () => rootRouteImport,
} as any)
const BstLinhaRoute = BstLinhaRouteImport.update({
  id: '/bst-linha',
  path: '/bst-linha',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bst-linha': typeof BstLinhaRoute
  '/bst-monarch': typeof BstMonarchRoute
  '/contato': typeof ContatoRoute
  '/elevadores': typeof ElevadoresRoute
  '/equipamentos': typeof EquipamentosRoute
  '/escadas': typeof EscadasRoute
  '/revenda': typeof RevendaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bst-linha': typeof BstLinhaRoute
  '/bst-monarch': typeof BstMonarchRoute
  '/contato': typeof ContatoRoute
  '/elevadores': typeof ElevadoresRoute
  '/equipamentos': typeof EquipamentosRoute
  '/escadas': typeof EscadasRoute
  '/revenda': typeof RevendaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bst-linha': typeof BstLinhaRoute
  '/bst-monarch': typeof BstMonarchRoute
  '/contato': typeof ContatoRoute
  '/elevadores': typeof ElevadoresRoute
  '/equipamentos': typeof EquipamentosRoute
  '/escadas': typeof EscadasRoute
  '/revenda': typeof RevendaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bst-linha'
    | '/bst-monarch'
    | '/contato'
    | '/elevadores'
    | '/equipamentos'
    | '/escadas'
    | '/revenda'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bst-linha'
    | '/bst-monarch'
    | '/contato'
    | '/elevadores'
    | '/equipamentos'
    | '/escadas'
    | '/revenda'
  id:
    | '__root__'
    | '/'
    | '/bst-linha'
    | '/bst-monarch'
    | '/contato'
    | '/elevadores'
    | '/equipamentos'
    | '/escadas'
    | '/revenda'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BstLinhaRoute: typeof BstLinhaRoute
  BstMonarchRoute: typeof BstMonarchRoute
  ContatoRoute: typeof ContatoRoute
  ElevadoresRoute: typeof ElevadoresRoute
  EquipamentosRoute: typeof EquipamentosRoute
  EscadasRoute: typeof EscadasRoute
  RevendaRoute: typeof RevendaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/revenda': {
      id: '/revenda'
      path: '/revenda'
      fullPath: '/revenda'
      preLoaderRoute: typeof RevendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escadas': {
      id: '/escadas'
      path: '/escadas'
      fullPath: '/escadas'
      preLoaderRoute: typeof EscadasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipamentos': {
      id: '/equipamentos'
      path: '/equipamentos'
      fullPath: '/equipamentos'
      preLoaderRoute: typeof EquipamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elevadores': {
      id: '/elevadores'
      path: '/elevadores'
      fullPath: '/elevadores'
      preLoaderRoute: typeof ElevadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bst-monarch': {
      id: '/bst-monarch'
      path: '/bst-monarch'
      fullPath: '/bst-monarch'
      preLoaderRoute: typeof BstMonarchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bst-linha': {
      id: '/bst-linha'
      path: '/bst-linha'
      fullPath: '/bst-linha'
      preLoaderRoute: typeof BstLinhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BstLinhaRoute: BstLinhaRoute,
  BstMonarchRoute: BstMonarchRoute,
  ContatoRoute: ContatoRoute,
  ElevadoresRoute: ElevadoresRoute,
  EquipamentosRoute: EquipamentosRoute,
  EscadasRoute: EscadasRoute,
  RevendaRoute: RevendaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
