/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as EscadasRouteImport } from './routes/escadas'
import { Route as ElevadoresRouteImport } from './routes/elevadores'
import { Route as ContatoBstRouteImport } from './routes/contato-bst'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as BstInfoRouteImport } from './routes/bst-info'
import { Route as BstRouteImport } from './routes/bst'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GaleriaSlugRouteImport } from './routes/galeria.$slug'

const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const EscadasRoute = EscadasRouteImport.update({
  id: '/escadas',
  path: '/escadas',
  getParentRoute: () => rootRouteImport,
} as any)
const ElevadoresRoute = ElevadoresRouteImport.update({
  id: '/elevadores',
  path: '/elevadores',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoBstRoute = ContatoBstRouteImport.update({
  id: '/contato-bst',
  path: '/contato-bst',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const BstInfoRoute = BstInfoRouteImport.update({
  id: '/bst-info',
  path: '/bst-info',
  getParentRoute: () => rootRouteImport,
} as any)
const BstRoute = BstRouteImport.update({
  id: '/bst',
  path: '/bst',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaSlugRoute = GaleriaSlugRouteImport.update({
  id: '/galeria/$slug',
  path: '/galeria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bst': typeof BstRoute
  '/bst-info': typeof BstInfoRoute
  '/contato': typeof ContatoRoute
  '/contato-bst': typeof ContatoBstRoute
  '/elevadores': typeof ElevadoresRoute
  '/escadas': typeof EscadasRoute
  '/portfolio': typeof PortfolioRoute
  '/galeria/$slug': typeof GaleriaSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bst': typeof BstRoute
  '/bst-info': typeof BstInfoRoute
  '/contato': typeof ContatoRoute
  '/contato-bst': typeof ContatoBstRoute
  '/elevadores': typeof ElevadoresRoute
  '/escadas': typeof EscadasRoute
  '/portfolio': typeof PortfolioRoute
  '/galeria/$slug': typeof GaleriaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bst': typeof BstRoute
  '/bst-info': typeof BstInfoRoute
  '/contato': typeof ContatoRoute
  '/contato-bst': typeof ContatoBstRoute
  '/elevadores': typeof ElevadoresRoute
  '/escadas': typeof EscadasRoute
  '/portfolio': typeof PortfolioRoute
  '/galeria/$slug': typeof GaleriaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bst'
    | '/bst-info'
    | '/contato'
    | '/contato-bst'
    | '/elevadores'
    | '/escadas'
    | '/portfolio'
    | '/galeria/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bst'
    | '/bst-info'
    | '/contato'
    | '/contato-bst'
    | '/elevadores'
    | '/escadas'
    | '/portfolio'
    | '/galeria/$slug'
  id:
    | '__root__'
    | '/'
    | '/bst'
    | '/bst-info'
    | '/contato'
    | '/contato-bst'
    | '/elevadores'
    | '/escadas'
    | '/portfolio'
    | '/galeria/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BstRoute: typeof BstRoute
  BstInfoRoute: typeof BstInfoRoute
  ContatoRoute: typeof ContatoRoute
  ContatoBstRoute: typeof ContatoBstRoute
  ElevadoresRoute: typeof ElevadoresRoute
  EscadasRoute: typeof EscadasRoute
  PortfolioRoute: typeof PortfolioRoute
  GaleriaSlugRoute: typeof GaleriaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escadas': {
      id: '/escadas'
      path: '/escadas'
      fullPath: '/escadas'
      preLoaderRoute: typeof EscadasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elevadores': {
      id: '/elevadores'
      path: '/elevadores'
      fullPath: '/elevadores'
      preLoaderRoute: typeof ElevadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato-bst': {
      id: '/contato-bst'
      path: '/contato-bst'
      fullPath: '/contato-bst'
      preLoaderRoute: typeof ContatoBstRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bst-info': {
      id: '/bst-info'
      path: '/bst-info'
      fullPath: '/bst-info'
      preLoaderRoute: typeof BstInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bst': {
      id: '/bst'
      path: '/bst'
      fullPath: '/bst'
      preLoaderRoute: typeof BstRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria/$slug': {
      id: '/galeria/$slug'
      path: '/galeria/$slug'
      fullPath: '/galeria/$slug'
      preLoaderRoute: typeof GaleriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BstRoute: BstRoute,
  BstInfoRoute: BstInfoRoute,
  ContatoRoute: ContatoRoute,
  ContatoBstRoute: ContatoBstRoute,
  ElevadoresRoute: ElevadoresRoute,
  EscadasRoute: EscadasRoute,
  PortfolioRoute: PortfolioRoute,
  GaleriaSlugRoute: GaleriaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
